definitions:
  services:
    docker:
      memory: 2048
  steps:
    - step: &Release-step
        name: Release step
        deployment: testing
        script: # Modify the commands below to build your repository.
            - docker version
            - docker build -t ${ENV}-mmk-dsa --build-arg REACT_APP_API=${LAP_URL} --build-arg BUILD_VERSION=${BITBUCKET_COMMIT} .

            - pipe: atlassian/aws-ecr-push-image:1.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ECR_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_ECR_SECRET_KEY
                AWS_DEFAULT_REGION: $AWS_ECR_REGION
                IMAGE_NAME: ${ENV}-mmk-dsa
                TAGS: 'latest'

            - pipe: atlassian/trigger-pipeline:4.2.1
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                REPOSITORY: 'mmk-platform'
                BRANCH_NAME: 'develop'
                CUSTOM_PIPELINE_NAME: 'deploy-mmk-web-${ENV}'

        services:
            - docker
        caches:
            - docker
pipelines:
  branches:
    master:
      - step:
          <<: *Release-step
          deployment: production
    develop:
      - step:
          <<: *Release-step
