export const STATES = [
  { code: 'AN', name: 'Andaman and Nicobar Islands' },
  { code: 'AP', name: 'Andhra Pradesh' },
  { code: 'AR', name: 'Arunāchal Pradesh' },
  { code: 'AS', name: 'Assam' },
  { code: 'BR', name: 'Bihār' },
  { code: 'CH', name: 'Chandigarh' },
  { code: 'CT', name: 'Chhattīsgarh' },
  { code: 'DH', name: 'Dādra and Nagar Haveli and Damān and Diu' },
  { code: 'DL', name: 'Delhi' },
  { code: 'GA', name: 'Goa' },
  { code: 'GJ', name: 'Gujarāt' },
  { code: 'HP', name: 'Himāchal Pradesh' },
  { code: 'HR', name: 'Haryāna' },
  { code: 'JH', name: 'Jhārkhand' },
  { code: 'JK', name: 'Jammu and Kashmīr' },
  { code: 'KA', name: 'Karnātaka' },
  { code: 'KL', name: 'Kerala' },
  { code: 'LA', name: 'Ladākh' },
  { code: 'LD', name: 'Lakshadweep' },
  { code: 'MH', name: 'Mahārāshtra' },
  { code: 'ML', name: 'Meghālaya' },
  { code: 'MN', name: 'Manipur' },
  { code: 'MP', name: 'Madhya Pradesh' },
  { code: 'MZ', name: 'Mizoram' },
  { code: 'NL', name: 'Nāgāland' },
  { code: 'OR', name: 'Odisha' },
  { code: 'PB', name: 'Punjab' },
  { code: 'PY', name: 'Puducherry' },
  { code: 'RJ', name: 'Rājasthān' },
  { code: 'SK', name: 'Sikkim' },
  { code: 'TG', name: 'Telangāna' },
  { code: 'TN', name: 'Tamil Nādu' },
  { code: 'TR', name: 'Tripura' },
  { code: 'UP', name: 'Uttar Pradesh' },
  { code: 'UT', name: 'Uttarākhand' },
  { code: 'WB', name: 'West Bengal' },
];
